version: '3.5'

services:
  todo-app-db:
    container_name: todo-app-db
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todo-app-db
    volumes:
       - todo-app-db-data:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - nat
    restart: unless-stopped

networks:
  nat:
    driver: bridge

volumes:
    todo-app-db-data: